In [5]:
#на паре делали это

%pip install -Uq numpy



Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

matrix1 =np.array( [
    [1, 1, 1],
    [1, 2, 3],
    [11, 12, 13],
    [11, 22, 33],

])
matrix2 =np.array( [
    [4, 5, 6],
    [7, 8, 9],
    [77, 12, 12],
    [2, 1, 33],

])

In [7]:
matrix1 * matrix2

array([[   4,    5,    6],
       [   7,   16,   27],
       [ 847,  144,  156],
       [  22,   22, 1089]])

In [8]:
matrix1 * 2 

array([[ 2,  2,  2],
       [ 2,  4,  6],
       [22, 24, 26],
       [22, 44, 66]])

In [9]:
matrix1 @ matrix2.T 

array([[  15,   24,  101,   36],
       [  32,   50,  137,  103],
       [ 182,  290, 1147,  463],
       [ 352,  550, 1507, 1133]])

In [10]:
matrix2 / 2

array([[ 2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5],
       [38.5,  6. ,  6. ],
       [ 1. ,  0.5, 16.5]])

In [11]:
matrix2 - matrix1

array([[  3,   4,   5],
       [  6,   6,   6],
       [ 66,   0,  -1],
       [ -9, -21,   0]])

In [12]:
matrix1 +  matrix2

array([[ 5,  6,  7],
       [ 8, 10, 12],
       [88, 24, 25],
       [13, 23, 66]])